# ==============================
# Configuration de la stack Docker
# ==============================

mysql:
  version: "8.0.43"     # Version de MySQL (8.0.43 stable, fixe)
  database: "todo_db"   # Nom de la base de données utilisée par l'app
  user: "todo_user"     # Utilisateur dédié à l'application
  password: "todo_pass" # Mot de passe de l'utilisateur
  root_password: "root_pass" # Mot de passe administrateur MySQL
  charset: "utf8mb4"    # Jeu de caractères recommandé (supporte les emojis)

phpmyadmin:
  version: "5.2"        # Version de phpMyAdmin (stable, fixe)
  port: 8080            # Port d'accès à phpMyAdmin dans le navigateur

backend:
  python_image: "python:3.11-slim"   # Image de base pour Flask (légère et récente)
  flask_env: "development"           # Mode d'exécution (development = reload, production = gunicorn)
  secret_key: "supersecret"          # Clé secrète Flask (sessions, sécurité)
  sqlalchemy_uri: "mysql+pymysql://todo_user:todo_pass@mysql:3306/todo_db?charset=utf8mb4"
  # Chaîne de connexion vers MySQL dans Docker avec charset UTF-8

frontend:
  node_image: "node:20"              # Image Node.js pour build du frontend
  port: 3000                         # Port local pour développement du frontend
  vite_api_url: "http://localhost/api" 
  # URL publique vers l’API Flask exposée par le proxy

proxy:
  choice: "traefik"     # Choix du reverse proxy (nginx ou traefik)
  port_http: 80         # Port HTTP exposé
  port_https: 443       # Port HTTPS exposé
  ssl_enabled: false    # Activer HTTPS/Let's Encrypt (false pour dev local, true pour prod avec domaine réel)
  dashboard: true       # Activer le tableau de bord de Traefik (visualisation des routes)
  domain: "localhost"   # Domaine utilisé (localhost pour dev, ou un vrai domaine en prod)

network:
  public: "public_net"  # Réseau exposant frontend + proxy
  internal: "internal_net" # Réseau privé pour DB, backend et phpMyAdmin

deploy:
  restart_policy: "unless-stopped" # Politique de redémarrage des conteneurs

monitoring:
  stack: "dozzle+cadvisor" # Monitoring minimal (dozzle+cadvisor) ou complet (prometheus+grafana)

documentation:
  format: "markdown"   # Format du fichier doc (Markdown pour GitHub)
